download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip","./EPC.zip")
unzip("EPC.zip")

library(data.table)
data=fread("household_power_consumption.txt",sep=";")
data=as.data.frame(data)
A=data[data$Date %in% c("1/2/2007","2/2/2007"),]
datetime <- strptime(paste(A$Date, A$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
B=as.numeric(A$Sub_metering_1)
C=as.numeric(A$Sub_metering_2)
D=as.numeric(A$Sub_metering_3)
E=as.numeric(A$Voltage)
G=as.numeric(A$Global_reactive_power)
H=as.numeric(A$Global_active_power)

png("plot4.png", width = 480, height = 480)
par(mar=c(4,4,4,4))
par(mfrow=c(2,2))
plot(datetime,H,type="scatter",xlab="",ylab="Global Active Power")
plot(datetime,E,type="scatter",xlab="datetime",ylab="Voltage")
plot(datetime,B,type="scatter",xlab="",ylab="Energy sub metering")
        lines(datetime,C,col="red")
        lines(datetime,D,col="blue")
        legend("topright",lty=c(1,1,1),col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),cex=0.75,bty="n")
plot(datetime,G,type="scatter",xlab="datetime",ylab="Global_reactive_power")
dev.off()
